### ISSUE TITLE
[Bug] Black Dashboard PRO React won't compile

### ISSUE THREAD

**Issue by dewhurstwill** [creativetimofficial/ct-black-dashboard-pro-react#21] opened 2020-01-09 11:40 UTC
### Version
latest
### Operating System
OSX Catalina 10.15.2
### Device
MacBook Pro 2017
### Browser & Version
Chrome Version 79.0.3945.88 (Official Build) (64-bit)
### Steps to reproduce
1. Download from https://www.creative-tim.com/
2. Download and install nodejs
3. Navigate and expand template zip
4. npm run install:clean
### What is expected?
Website loads normally
### What is actually happening?
./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0 (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./src/assets/scss/black-dashboard-pro-react.scss?v=1.0.0)
Module not found: Can't resolve './black-dashboard-pro-react/img/asc.gif' in '/Users/wdewhurst/Downloads/POC/src/assets/scss'

---

**Comment by einazare** [comment] 2020-01-09 11:47
Hello there, @willdewhust ,

This issue was also addressed here: #20 
To solve it, please run the following:
```
npm i -E node-sass@4.13.0
npm install
npm start
```
If this does not fix your issue, please read the other issue for more insights.
Hope you are OK with closing this issue, and if you have further questions, move them on the other issue, since this is kind of a duplicate of the other one.

Best,
Manu

**Closed as completed by einazare** 2020-01-09 11:47 UTC
Labels: bug
